package entity;

import java.time.LocalDate;

/**
 * Represents a feedback entry generated by the system.
 * Each entry includes the date, AI analysis, correlation insights, and recommendations.
 */
public class FeedbackEntry {
    private final LocalDate date;
    private final String aiAnalysis;
    private final String correlationData;
    private final String recommendations;

    /**
     * Constructs a FeedbackEntry with all fields.
     *
     * @param date            The date the feedback was generated
     * @param aiAnalysis      Summary generated by AI about the user's patterns
     * @param correlationData Detected correlations (e.g., between tasks, moods, productivity)
     * @param recommendations Suggested improvements or next steps
     */
    public FeedbackEntry(LocalDate date, String aiAnalysis, String correlationData, String recommendations) {
        this.date = date;
        this.aiAnalysis = aiAnalysis;
        this.correlationData = correlationData;
        this.recommendations = recommendations;
    }

    /**
     * return a string with all feedback details
     * @return A formatted string containing all feedback details
     */
    public String toString() {
        return "Feedback Entry for";
    }
}
